package exercise.entity;

public record Product(Long id, String name, String category, Double price) {
    // Constructor, getters, and setters are automatically generated by the record.

    // Override toString() method to display the details of the product record
    @Override
    public String toString() {
        return  "Id:" + id +  "\n" +
                "Name:" + name + "\n" +
                "Category:" + category + "\n" +
                "Price:" + price + "\n";
    }
}
